### ISSUE TITLE
Feature request: Allow SSL certificates installation for SSL access to the API

### ISSUE THREAD

**Issue by hedgemybets** [homewizard/api-documentation#100]
I saw the feature request for authentication, which I also favor. To go along with that security measure, it would be nice to be able to install SSL certificates to allow for SSL access to the API.

**Comment by DCSBL** [comment]
Thank you for your feature requests. we are currently in the design phase to update the API to an authenticated variant as mentioned in #99. This update also adds HTTPS support. I can't give any more details but I hope this answers your question.
