### ISSUE TITLE
Update interval set at 10s

### ISSUE THREAD

**Issue by devdems** [homewizard/api-documentation#102]
How can we shorten the update interval from 10s to 5s or even 1s? My Iskra meter is pushing values on P1 every second as it has DSMR=5 standard.

**Comment by DCSBL** [comment]
Please read all about update frequency at [this page](https://api-documentation.homewizard.com/docs/getting-started#data-update-frequency).

To summarize: Your smart meter determines the update frequency. If you are receiving data every 10 seconds, you should contact your net supplier to resolve this issue.

If you are discussing update frequency on another platform, such as Home Assistant, please direct your question to the appropriate platform.

**Comment by devdems** [comment]
Hi, it is in fact for the Home Assistant. Let me open it there. Tnx.
