### ISSUE TITLE
Feature request: password protect the local API

### ISSUE THREAD

**Issue by jhaand** [homewizard/api-documentation#99]
Hi, 

I really like the possibilities of the HWE-P1 especially how easy it is to read everything via  the local API in JSON. 

However, I would to be able to limit access to  the local API via a password. Is this possible?
At this moment everyone on the network can read all the information about our power meter.

Thanks in advance.

**Comment by DCSBL** [comment]
Hi! Good question. Currently it is not possible to limit access to the API, other than disabling the API completely. For now you have to isolate the device in your network using firewall rules.

But, we are currently in the design phase to update the API to an authenticated variant. We can't make any promises about the details or timeline yet, but it will not happen overnight.

Can I reach out to you when we need beta-testers for this feature?

**Comment by jhaand** [comment]
Thank you for the quick response.   
Looking forward to the update.
